language: python
python:
    - "3.7.6"

services:
    - docker

before_script: pip install docker-compose
before_script: docker-compose build

script:
    - docker-compose run --rm app sh -c "python manage.py test && flake8"